### ISSUE TITLE
Many failing Boundwith parts. 

### ISSUE THREAD

**Issue by fontanka16** [FOLIO-FSE/MARC21-To-FOLIO#113]
![image](https://user-images.githubusercontent.com/1894384/150130813-6186c147-1f54-4209-b2cc-63a605ba532d.png)
It seems there are BW parts being constructed for Holdingsrecords that does not exist, leading to many failing BW postings.

**Comment by fontanka16** [comment]
@branchedelac  If you have anything to add, please add it here.

I suspect BW items are being constructed too early in the holdings generation process.

**Comment by branchedelac** [comment]
1. Select an error row from the posting log:
`Row 39067	HTTP 422	 Cannot set bound_with_part.holdingsrecordid = 359bbe1e-f933-5107-b997-d41f0d4c5c7d because it does not exist in holdings_record.id.`

2. Take the holdingsrecordid, and search for this in the extradata file. In this case, I found two entries which were identical apart from the object UUID.
`boundwithPart	{"id": "880b8cdf-5591-41ca-945e-b084210ba288", "holdingsRecordId": "359bbe1e-f933-5107-b997-d41f0d4c5c7d", "itemId": "f257e076-2804-5d5e-a08a-6ba81944fa14"}`

3. Take the itemId, and search for this in the the file of generated items.
`{"id": "f257e076-2804-5d5e-a08a-6ba81944fa14", "metadata": {"createdDate": "2022-01-14T18:19:29.077", "createdByUserId": "f22a3237-bf6e-44ac-8a2b-835e4d730331", "updatedDate": "2022-01-14T18:19:29.077", "updatedByUserId": "f22a3237-bf6e-44ac-8a2b-835e4d730331"}, "holdingsRecordId": "ba0a7cb8-82b6-5008-af63-a9c6933c6701", "formerIds": ["['b10116254', 'b1234266x']", "i10116540"], "barcode": "31826007413066", "volume": "no.84 1984", "copyNumber": "1", "notes": [{"itemNoteTypeId": "7da98fdd-69ed-4bbb-ba1e-0e157b81efb5", "note": "0", "staffOnly": true}], "status": {"name": "Available", "date": "2022-01-14T18:19:29.077503"}, "materialTypeId": "947bbbea-d84f-4cb6-90e4-cecd49b81e74", "permanentLoanTypeId": "2f6d2ef9-4ccb-4e39-86c4-bbc59a666e6b"}`

4. If this item was created, that means a holding was also created. Get the barcode from the item object, and search for this in FOLIO.
![image](https://user-images.githubusercontent.com/44287646/150158370-de6fdec9-9102-474c-a781-9c3633b399c6.png)
This gives you a good view of what has been created, and how the records have been linked together. This will be even clearer in Kiwi, where you'll be able to see the boundwith relationships.

5. Get the UUID of the holding that this item is attached to, in this case ba0a7cb8-82b6-5008-af63-a9c6933c6701. 

Check if this UUID is present in the extradata file. It is!
`boundwithPart	{"id": "974d9543-36e5-436f-b9c6-921b3d5db0c2", "holdingsRecordId": "ba0a7cb8-82b6-5008-af63-a9c6933c6701", "itemId": "7ce65402-0760-5af7-b528-dd427d190741"}`

Note that the itemId is not the same as the one in 2.

Check if the holdingsId is mentioned among the errors in the posting log. It is!
`Row 39231	HTTP 422	 lower(f_unaccent(jsonb ->> 'itemId'::text)), lower(f_unaccent(jsonb ->> 'holdingsRecordId'::text)) value already exists in table bound_with_part: 7ce65402-0760-5af7-b528-dd427d190741, ba0a7cb8-82b6-5008-af63-a9c6933c6701`

Somehow, the same boundwith -- in different aspects -- is involved in two different errors.

**Comment by branchedelac** [comment]
I don't know if this makes a difference, but I (reverse) analysed the record(s) in my comment above and...
<img width="523" alt="Drawing1" src="https://user-images.githubusercontent.com/44287646/150180148-09e2457f-5499-414e-a01d-abe011f6100a.png">

**Comment by fontanka16** [comment]
@branchedelac  I have a couple of theories. I will wait until I get there with MSU-LM for the second run.

**Comment by fontanka16** [comment]
@branchedelac closing this since I have not been able to reproduce this since my last update.
